//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalantOnboardingTask1_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int CustomerId { get; set; }
        public int StoreId { get; set; }
        public System.DateTime DateSold { get; set; }
    
        public virtual Customer_ Customer_ { get; set; }
        public virtual Product_ Product_ { get; set; }
        public virtual Store_ Store_ { get; set; }
    }
}
